# Form implementation generated from reading ui file 'password_generate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerate(object):
    def setupUi(self, PasswordGenerate):
        PasswordGenerate.setObjectName("PasswordGenerate")
        PasswordGenerate.resize(400, 186)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("密码.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PasswordGenerate.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordGenerate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=PasswordGenerate)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=PasswordGenerate)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=PasswordGenerate)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.checkBox_lower = QtWidgets.QCheckBox(parent=PasswordGenerate)
        self.checkBox_lower.setObjectName("checkBox_lower")
        self.horizontalLayout_3.addWidget(self.checkBox_lower)
        self.checkBox_upper = QtWidgets.QCheckBox(parent=PasswordGenerate)
        self.checkBox_upper.setObjectName("checkBox_upper")
        self.horizontalLayout_3.addWidget(self.checkBox_upper)
        self.checkBox_digit = QtWidgets.QCheckBox(parent=PasswordGenerate)
        self.checkBox_digit.setObjectName("checkBox_digit")
        self.horizontalLayout_3.addWidget(self.checkBox_digit)
        self.checkBox_marks = QtWidgets.QCheckBox(parent=PasswordGenerate)
        self.checkBox_marks.setObjectName("checkBox_marks")
        self.horizontalLayout_3.addWidget(self.checkBox_marks)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=PasswordGenerate)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_pwd_length = QtWidgets.QLineEdit(parent=PasswordGenerate)
        self.lineEdit_pwd_length.setObjectName("lineEdit_pwd_length")
        self.horizontalLayout_2.addWidget(self.lineEdit_pwd_length)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_pwd = QtWidgets.QLineEdit(parent=PasswordGenerate)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.horizontalLayout_4.addWidget(self.lineEdit_pwd)
        self.pushButton_generate_pwd = QtWidgets.QPushButton(parent=PasswordGenerate)
        self.pushButton_generate_pwd.setObjectName("pushButton_generate_pwd")
        self.horizontalLayout_4.addWidget(self.pushButton_generate_pwd)
        self.pushButton_save_pwd = QtWidgets.QPushButton(parent=PasswordGenerate)
        self.pushButton_save_pwd.setObjectName("pushButton_save_pwd")
        self.horizontalLayout_4.addWidget(self.pushButton_save_pwd)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(PasswordGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerate)

    def retranslateUi(self, PasswordGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerate.setWindowTitle(_translate("PasswordGenerate", "密码生成器"))
        self.label.setText(_translate("PasswordGenerate", "网络地址"))
        self.label_2.setText(_translate("PasswordGenerate", "密码组合"))
        self.checkBox_lower.setText(_translate("PasswordGenerate", "小写"))
        self.checkBox_upper.setText(_translate("PasswordGenerate", "大写"))
        self.checkBox_digit.setText(_translate("PasswordGenerate", "数字"))
        self.checkBox_marks.setText(_translate("PasswordGenerate", "符号"))
        self.label_3.setText(_translate("PasswordGenerate", "密码位数"))
        self.pushButton_generate_pwd.setText(_translate("PasswordGenerate", "生成密码"))
        self.pushButton_save_pwd.setText(_translate("PasswordGenerate", "保存"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordGenerate = QtWidgets.QDialog()
    ui = Ui_PasswordGenerate()
    ui.setupUi(PasswordGenerate)
    PasswordGenerate.show()
    sys.exit(app.exec())
