# Form implementation generated from reading ui file 'json_tool.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TranslateJson(object):
    def setupUi(self, TranslateJson):
        TranslateJson.setObjectName("TranslateJson")
        TranslateJson.resize(405, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("json.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        TranslateJson.setWindowIcon(icon)
        TranslateJson.setStyleSheet(".QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7f8, stop: 1 #dadbdc);\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dadbdc;\n"
"    box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.1);\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e6e7e8, stop: 1 #c8c9ca);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbdc, stop: 1 #b0b1b3);\n"
"}\n"
"\n"
".QLabel{\n"
"     font-weight: bold;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(TranslateJson)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=TranslateJson)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_json_text = QtWidgets.QTextEdit(parent=TranslateJson)
        self.textEdit_json_text.setObjectName("textEdit_json_text")
        self.horizontalLayout_3.addWidget(self.textEdit_json_text)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_formate = QtWidgets.QPushButton(parent=TranslateJson)
        self.pushButton_formate.setObjectName("pushButton_formate")
        self.horizontalLayout.addWidget(self.pushButton_formate)
        self.pushButton_unformate = QtWidgets.QPushButton(parent=TranslateJson)
        self.pushButton_unformate.setObjectName("pushButton_unformate")
        self.horizontalLayout.addWidget(self.pushButton_unformate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_paste = QtWidgets.QPushButton(parent=TranslateJson)
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.horizontalLayout_2.addWidget(self.pushButton_paste)
        self.pushButton_clear = QtWidgets.QPushButton(parent=TranslateJson)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_2.addWidget(self.pushButton_clear)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(TranslateJson)
        QtCore.QMetaObject.connectSlotsByName(TranslateJson)

    def retranslateUi(self, TranslateJson):
        _translate = QtCore.QCoreApplication.translate
        TranslateJson.setWindowTitle(_translate("TranslateJson", "JSON工具"))
        self.label_2.setText(_translate("TranslateJson", "请粘贴JSON文本："))
        self.pushButton_formate.setText(_translate("TranslateJson", "格式化JSON"))
        self.pushButton_unformate.setText(_translate("TranslateJson", "反格式化JSON"))
        self.pushButton_paste.setText(_translate("TranslateJson", "复制"))
        self.pushButton_clear.setText(_translate("TranslateJson", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TranslateJson = QtWidgets.QDialog()
    ui = Ui_TranslateJson()
    ui.setupUi(TranslateJson)
    TranslateJson.show()
    sys.exit(app.exec())
