# Form implementation generated from reading ui file 'calculate_bmi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalculateBmi(object):
    def setupUi(self, CalculateBmi):
        CalculateBmi.setObjectName("CalculateBmi")
        CalculateBmi.resize(526, 288)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("皮重设置.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CalculateBmi.setWindowIcon(icon)
        CalculateBmi.setStyleSheet("* {\n"
"    font-size:14px;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CalculateBmi)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=CalculateBmi)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_height = QtWidgets.QLineEdit(parent=CalculateBmi)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.horizontalLayout.addWidget(self.lineEdit_height)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=CalculateBmi)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_weight = QtWidgets.QLineEdit(parent=CalculateBmi)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.horizontalLayout_2.addWidget(self.lineEdit_weight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_calculate = QtWidgets.QPushButton(parent=CalculateBmi)
        self.pushButton_calculate.setStyleSheet("")
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_tips = QtWidgets.QLabel(parent=CalculateBmi)
        self.label_tips.setStyleSheet("*{\n"
"    font-size:12px;\n"
"}")
        self.label_tips.setWordWrap(True)
        self.label_tips.setObjectName("label_tips")
        self.horizontalLayout_3.addWidget(self.label_tips)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(parent=CalculateBmi)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.label_result = QtWidgets.QLabel(parent=CalculateBmi)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 7)
        self.verticalLayout_3.setStretch(1, 3)

        self.retranslateUi(CalculateBmi)
        QtCore.QMetaObject.connectSlotsByName(CalculateBmi)

    def retranslateUi(self, CalculateBmi):
        _translate = QtCore.QCoreApplication.translate
        CalculateBmi.setWindowTitle(_translate("CalculateBmi", "BMI-C"))
        self.label.setText(_translate("CalculateBmi", "身高（cm）："))
        self.label_2.setText(_translate("CalculateBmi", "体重（kg）："))
        self.pushButton_calculate.setText(_translate("CalculateBmi", "计算"))
        self.label_tips.setText(_translate("CalculateBmi", "提示：\n"
"1、中国成人居民BM川衡量标准是小于等于18.4为消瘦，18.5-23.9为正常，24-\n"
"27.9为超重，大于等于28为肥胖。\n"
"2、最理想的BM川数值为22，理想体重=22×身高2（米），±10%波动"))
        self.label_title.setText(_translate("CalculateBmi", "您的计算结果："))
        self.label_result.setText(_translate("CalculateBmi", "BMI:27.18属于超重您的理想体重为：68KG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalculateBmi = QtWidgets.QDialog()
    ui = Ui_CalculateBmi()
    ui.setupUi(CalculateBmi)
    CalculateBmi.show()
    sys.exit(app.exec())
