# Form implementation generated from reading ui file 'extract_phone.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExtractPhoneNum(object):
    def setupUi(self, ExtractPhoneNum):
        ExtractPhoneNum.setObjectName("ExtractPhoneNum")
        ExtractPhoneNum.resize(503, 386)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("工具.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ExtractPhoneNum.setWindowIcon(icon)
        ExtractPhoneNum.setStyleSheet(".QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7f8, stop: 1 #dadbdc);\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dadbdc;\n"
"    box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.1);\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e6e7e8, stop: 1 #c8c9ca);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbdc, stop: 1 #b0b1b3);\n"
"}")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ExtractPhoneNum)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_input = QtWidgets.QPlainTextEdit(parent=ExtractPhoneNum)
        self.plainTextEdit_input.setObjectName("plainTextEdit_input")
        self.horizontalLayout.addWidget(self.plainTextEdit_input)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(parent=ExtractPhoneNum)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.horizontalLayout.addWidget(self.plainTextEdit_result)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_extract = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_extract.setObjectName("pushButton_extract")
        self.verticalLayout.addWidget(self.pushButton_extract)
        self.pushButton_email = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_email.setObjectName("pushButton_email")
        self.verticalLayout.addWidget(self.pushButton_email)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_sfz = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_sfz.setObjectName("pushButton_sfz")
        self.verticalLayout_2.addWidget(self.pushButton_sfz)
        self.pushButton_carnum = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_carnum.setObjectName("pushButton_carnum")
        self.verticalLayout_2.addWidget(self.pushButton_carnum)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_banknum = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_banknum.setObjectName("pushButton_banknum")
        self.verticalLayout_3.addWidget(self.pushButton_banknum)
        self.pushButton_ipdir = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_ipdir.setObjectName("pushButton_ipdir")
        self.verticalLayout_3.addWidget(self.pushButton_ipdir)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_paste = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.verticalLayout_4.addWidget(self.pushButton_paste)
        self.pushButton_clear = QtWidgets.QPushButton(parent=ExtractPhoneNum)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_4.addWidget(self.pushButton_clear)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ExtractPhoneNum)
        QtCore.QMetaObject.connectSlotsByName(ExtractPhoneNum)

    def retranslateUi(self, ExtractPhoneNum):
        _translate = QtCore.QCoreApplication.translate
        ExtractPhoneNum.setWindowTitle(_translate("ExtractPhoneNum", "要素提取工具1.0"))
        self.pushButton_extract.setText(_translate("ExtractPhoneNum", "提取手机号"))
        self.pushButton_email.setText(_translate("ExtractPhoneNum", "提取邮箱"))
        self.pushButton_sfz.setText(_translate("ExtractPhoneNum", "提取身份证号"))
        self.pushButton_carnum.setText(_translate("ExtractPhoneNum", "提取车牌号码"))
        self.pushButton_banknum.setText(_translate("ExtractPhoneNum", "提取银行卡号"))
        self.pushButton_ipdir.setText(_translate("ExtractPhoneNum", "提取IP地址"))
        self.pushButton_paste.setText(_translate("ExtractPhoneNum", "复制结果"))
        self.pushButton_clear.setText(_translate("ExtractPhoneNum", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExtractPhoneNum = QtWidgets.QDialog()
    ui = Ui_ExtractPhoneNum()
    ui.setupUi(ExtractPhoneNum)
    ExtractPhoneNum.show()
    sys.exit(app.exec())
